---
detectors:
  DataClump:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
  TooManyStatements:
    max_statements: 10
    enabled: false
  UtilityFunction:
    enabled: false
