AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
LineLength:
  Max: 100
Lint/ScriptPermission:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
