AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/**/*'
LineLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ClassVars:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
Style/NumericLiterals:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
